import {Platform, StyleSheet} from 'react-native';
import {Colors, Fonts, Metrics, typoGraphy} from '../theme';

const CommonStyle = StyleSheet.create({
  backArrowIconView: {
    left: Metrics.rfv(15),
    marginTop: Metrics.rfv(10),
    padding: Metrics.rfv(2),
  },
  button: {
    alignItems: 'center',
    backgroundColor: Colors.black,
    justifyContent: 'center',
    textTransform: 'uppercase',
    marginTop: Metrics.rfv(20),
    width: '100%',
  },
  center: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabBarLabelStyle: {
    fontFamily: Fonts.Regular,
    fontSize: typoGraphy.badgeText,
    fontWeight: '400',
    lineHeight: Metrics.rfv(16),
    position: 'absolute',
    top: Metrics.rfv(40),
  },
  checkMainView: {
    marginBottom: Metrics.rfv(3),
    marginTop: Metrics.rfv(10),
    paddingHorizontal: Metrics.rfv(20),
  },
  checkbox: {
    height: Metrics.rfv(20),
    marginTop: Metrics.rfv(2),
    width: Metrics.rfv(20),
  },
  chipView: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Metrics.rfv(10),
    paddingVertical: Metrics.rfv(5),
  },
  commonRow: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderColor: Colors.outline,
    borderRadius: Metrics.rfv(2),
    borderWidth: Metrics.rfv(1),
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: Platform.OS === 'ios' ? Metrics.rfv(16) : Metrics.rfv(5),
  },
  dashLineView: {
    borderColor: Colors.primary,
    borderStyle: 'dashed',
    borderWidth: Metrics.rfv(1.5),
    margin: -Metrics.rfv(2),
    marginTop: Metrics.rfv(10),
  },
  disableMainTextInputView: {
    alignItems: 'center',
    borderRadius: Metrics.rfv(5),
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingLeft: Metrics.rfv(10),
    paddingRight: Metrics.rfv(5),
    paddingVertical: Metrics.rfv(5),
  },
  dropDownStyle: {
    backgroundColor: Colors.white,
    borderColor: Colors.outline,
    borderRadius: Metrics.rfv(3),
    borderWidth: Metrics.rfv(1),
    flex: 1,
    height: Metrics.rfv(40),
    marginTop: Metrics.rfv(1),
    paddingHorizontal: Metrics.rfv(8),
  },
  flatListView: {
    flex: 1,
    width: Metrics.screenWidth - Metrics.rfv(20),
  },
  flex: {
    flex: 1,
  },
  flexCheckBox: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: Metrics.rfv(5),
  },
  flexGrow: {
    flexGrow: 1,
  },
  genderView: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flex: 1,
    flexDirection: 'row',
    marginTop: Metrics.rfv(10),
    paddingVertical: Metrics.rfv(5),
  },
  halfWidth: {
    width: Metrics.rfv(150),
  },
  iconStyle: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  inputStyle: {
    borderColor: Colors.outline,
    borderRadius: Metrics.rfv(5),
    borderWidth: Metrics.rfv(1.5),
  },
  lineView: {
    borderBottomColor: Colors.outline,
    borderBottomWidth: Metrics.rfv(1),
    marginTop: Metrics.rfv(8),
    width: '100%',
  },
  main: {
    backgroundColor: Colors.white,
    flex: 1,
  },
  mainCheckBoxView: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  mainChipView: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: Metrics.rfv(10),
  },
  mainInputView: {
    marginBottom: Metrics.rfv(10),
  },
  mainItemView: {
    backgroundColor: Colors.white,
    borderColor: Colors.primary,
    borderRadius: Metrics.rfv(5),
    flex: 1,
    marginBottom: Metrics.rfv(10),
    marginTop: Metrics.rfv(8),
  },
  mainTextInputView: {
    alignItems: 'center',
    borderColor: Colors.outline,
    borderRadius: Metrics.rfv(5),
    borderWidth: Metrics.rfv(1.5),
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingLeft: Metrics.rfv(10),
    paddingRight: Metrics.rfv(5),
    paddingVertical: Metrics.rfv(5),
  },
  mainViewTextInputView: {
    alignItems: 'center',
    borderRadius: Metrics.rfv(5),
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingLeft: Metrics.rfv(10),
    paddingRight: Metrics.rfv(5),
    paddingVertical: Metrics.rfv(5),
  },
  mainViewTypeContainer: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  mainViewTypeView: {
    alignItems: 'center',
    backgroundColor: Colors.chipBack,
    borderRadius: Metrics.rfv(5),
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: Metrics.rfv(5),
    padding: Metrics.rfv(8),
  },
  row: {
    flexDirection: 'row',
  },
  rowCenter: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  rowWithCenter: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  rowWithCenterInputView: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: Metrics.rfv(5),
  },
  tabBarStyle: {
    // borderRadius: Metrics.rfv(12),
    // elevation: 6,
    // height: Metrics.rfv(64),
    justifyContent: 'center',
    // shadowColor: Colors.shadow,
    // shadowOffset: {
    //   width: Metrics.rfv(0),
    //   height: Metrics.rfv(-4.17),
    // },
    // shadowOpacity: Metrics.rfv(0.18),
    // shadowRadius: Metrics.rfv(11.77),
    backgroundColor: Colors.black,
    width: Metrics.screenWidth,
  },
  topView: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
});

export default CommonStyle;
